---
{{- if .Values.celeryBeat.enabled }}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}-celery-beat
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: nautobot-celery-beat
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  revisionHistoryLimit: {{ .Values.celeryBeat.revisionHistoryLimit | int }}
  {{- if .Values.celeryBeat.updateStrategy }}
  strategy: {{- toYaml .Values.celeryBeat.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: nautobot-celery-beat
  template:
    metadata:
      {{- if .Values.celeryBeat.podAnnotations }}
      annotations: {{- include "common.tplvalues.render" (dict "value" .Values.celeryBeat.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: nautobot-celery-beat
        {{- if .Values.celeryBeat.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.celeryBeat.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.serviceAccount.name }}
      serviceAccountName: {{ template "nautobot.serviceAccountName" . }}
      {{- end }}
      {{- include "nautobot.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.celeryBeat.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.celeryBeat.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.celeryBeat.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.celeryBeat.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.celeryBeat.podAffinityPreset "component" "nautobot-celery-beat" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.celeryBeat.podAntiAffinityPreset "component" "nautobot-celery-beat" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.celeryBeat.nodeAffinityPreset.type "key" .Values.celeryBeat.nodeAffinityPreset.key "values" .Values.celeryBeat.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.celeryBeat.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.celeryBeat.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.celeryBeat.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.celeryBeat.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.celeryBeat.priorityClassName }}
      priorityClassName: {{ .Values.celeryBeat.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.celeryBeat.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.celeryBeat.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      initContainers:
        {{- if .Values.celeryBeat.initContainers }}
          {{- include "common.tplvalues.render" (dict "value" .Values.celeryBeat.initContainers "context" $) | nindent 8 }}
        {{- end }}
      containers:
        - name: nautobot-celery-beat
          tty: true
          image: {{ template "nautobot.image" . }}
          imagePullPolicy: {{ .Values.nautobot.image.pullPolicy }}
          {{- if .Values.celeryBeat.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.celeryBeat.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.celeryBeat.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.celeryBeat.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.celeryBeat.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.celeryBeat.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.celeryBeat.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.celeryBeat.args "context" $) | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.celeryBeat.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.celeryBeat.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "common.names.fullname" . }}-env
            - secretRef:
                name: {{ include "common.names.fullname" . }}-env
            {{- if .Values.celeryBeat.extraEnvVarsCM }}
            {{- range .Values.celeryBeat.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" . "context" $) }}
            {{- end }}
            {{- end }}
            {{- if .Values.celeryBeat.extraEnvVarsSecret }}
            {{- range .Values.celeryBeat.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" . "context" $) }}
            {{- end }}
            {{- end }}
          {{- if .Values.celeryBeat.resources }}
          resources: {{- toYaml .Values.celeryBeat.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.celeryBeat.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.celeryBeat.livenessProbe "enabled") "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.celeryBeat.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.celeryBeat.readinessProbe "enabled") "context" $) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: "git-repos"
              mountPath: "/opt/nautobot/git"
            {{- if .Values.nautobot.config }}
            - name: "nautobot-config"
              mountPath: "/opt/nautobot/nautobot_config.py"
              subPath: "nautobot_config.py"
            {{- end }}
            {{- if .Values.celeryBeat.extraVolumeMounts }}
            {{- include "common.tplvalues.render" ( dict "value" .Values.celeryBeat.extraVolumeMounts "context" $) | nindent 12 }}
            {{- end }}
        {{- if .Values.celeryBeat.sidecars }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.celeryBeat.sidecars "context" $) | nindent 8 }}
        {{- end }}
      volumes:
        - name: "git-repos"
          emptyDir: {}
        {{- if .Values.nautobot.config }}
        - name: "nautobot-config"
          configMap:
            name: {{ include "common.names.fullname" . }}-config
        {{- end }}
        {{- if .Values.celeryBeat.extraVolumes }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.celeryBeat.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
{{- end }}
