---
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: nautobot
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.nautobot.replicaCount }}
  {{- if .Values.nautobot.updateStrategy }}
  strategy: {{- toYaml .Values.nautobot.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: nautobot
  template:
    metadata:
      {{- if .Values.nautobot.podAnnotations }}
      annotations: {{- include "common.tplvalues.render" (dict "value" .Values.nautobot.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: nautobot
        {{- if .Values.nautobot.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.nautobot.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      revisionHistoryLimit: {{ .Values.nautobot.revisionHistoryLimit | int }}
      {{- if .Values.serviceAccount.name }}
      serviceAccountName: {{ template "nautobot.serviceAccountName" . }}
      {{- end }}
      {{- include "nautobot.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.nautobot.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.nautobot.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.nautobot.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.nautobot.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.nautobot.podAffinityPreset "component" "nautobot" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.nautobot.podAntiAffinityPreset "component" "nautobot" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.nautobot.nodeAffinityPreset.type "key" .Values.nautobot.nodeAffinityPreset.key "values" .Values.nautobot.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.nautobot.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.nautobot.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.nautobot.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.nautobot.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.nautobot.priorityClassName }}
      priorityClassName: {{ .Values.nautobot.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.nautobot.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.nautobot.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      initContainers:
        {{- if .Values.nautobot.initContainers }}
          {{- include "common.tplvalues.render" (dict "value" .Values.nautobot.initContainers "context" $) | nindent 8 }}
        {{- end }}
      containers:
        - name: nautobot
          image: {{ template "nautobot.image" . }}
          imagePullPolicy: {{ .Values.nautobot.image.pullPolicy }}
          {{- if .Values.nautobot.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.nautobot.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.nautobot.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.nautobot.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.nautobot.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.nautobot.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.nautobot.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.nautobot.args "context" $) | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.nautobot.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.nautobot.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "common.names.fullname" . }}-env
            - secretRef:
                name: {{ include "common.names.fullname" . }}-env
            {{- if .Values.nautobot.extraEnvVarsCM }}
            {{- range .Values.nautobot.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" . "context" $) }}
            {{- end }}
            {{- end }}
            {{- if .Values.nautobot.extraEnvVarsSecret }}
            {{- range .Values.nautobot.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" . "context" $) }}
            {{- end }}
            {{- end }}
          {{- if .Values.nautobot.resources }}
          resources: {{- toYaml .Values.nautobot.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.nautobot.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.nautobot.livenessProbe "enabled") "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.nautobot.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.nautobot.readinessProbe "enabled") "context" $) | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- if (include "nautobot.extraVolumeMounts" .) }}
          {{- include "common.tplvalues.render" (dict "value" (include "nautobot.extraVolumeMounts" .) "context" $) | nindent 12 }}
          {{- end }}
          ports:
            - name: "https"
              containerPort: 8443
            - name: "http"
              containerPort: 8080
        {{- if .Values.nautobot.sidecars }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.nautobot.sidecars "context" $) | nindent 8 }}
        {{- end }}
      {{- if (include "nautobot.extraVolumes" .) }}
      volumes:
        {{- include "common.tplvalues.render" (dict "value" (include "nautobot.extraVolumes" .) "context" $) | nindent 8 }}
      {{- end }}
